services:
  - type: web
    name: smtp-telegram-bot
    dockerfileInstallCommand: |
      apt-get update && apt-get install -y curl &&
      curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8525848016:AAF8yTVahsO2wjO-Lj84Zx5i0d_yrMQHG54
